### What is NumPy?
- `NumPy is a Python library used for working with arrays.`

- `It also has functions for working in domain of linear algebra, fourier transform, and matrices.`

- `NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.`

- `NumPy stands for Numerical Python.`

### Installation of NumPy
- `If you have Python and PIP already installed on a system, then installation of NumPy is very easy.`

- `Install it using this command: !pip install numpy`

### Import NumPy
- `Once NumPy is installed, import it in your applications by adding the **import** keyword:`

In [1]:
# Example

import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### NumPy as np
- `NumPy is usually imported under the np alias.`

- `alias: In Python alias are an alternate name for referring to the same thing.`

- `Create an alias with the as keyword while importing:`

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Checking NumPy Version
+ `The version string is stored under  __version__  attribute.`

In [3]:
#Example

import numpy as np

print(np.__version__)

1.20.1


### Create a NumPy ndarray Object
+ NumPy is used to work with arrays. The array object in NumPy is called **ndarray**.

+ We can create a NumPy ndarray object by using the array() function.

In [4]:
# example

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


### Dimensions in Arrays
+ A dimension in arrays is one level of array depth (nested arrays).

### 0-D Arrays
+ 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [7]:
import numpy as np

arr = np.array(42)

print(arr)

42


### 1-D Arrays

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays

In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays

In [11]:
import numpy as np

arr = np.array([[[1, 2], [3, 4], [5, 6]]])

print(arr)

[[[1 2]
  [3 4]
  [5 6]]]


### Check Number of Dimensions
+ NumPy Arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have

In [13]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2], [3, 4], [5, 6]]])

print('number of dimensions :',a.ndim)
print('number of dimensions :',b.ndim)
print('number of dimensions :',c.ndim)
print('number of dimensions :',d.ndim)

number of dimensions : 0
number of dimensions : 1
number of dimensions : 2
number of dimensions : 3


### NumPy Array Indexing

+ **Access Array Elements**

+ `Array indexing is the same as accessing an array element.`

+ `You can access an array element by referring to its index number.`

+ `The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.`

In [14]:
# Get the first element from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [15]:
# Get the second element from the following array.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


### Access 2-D Arrays
+ To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

+ Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [17]:
# Access the element on the first row, second column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

print('element on the first row, second column: ', arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
element on the first row, second column:  2


In [18]:
# Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

print('5th element on 2nd row: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row:  10


### Access 3-D Arrays
+ To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [20]:
# Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [24]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Sorting Arrays
+ Sorting means putting elements in an ordered sequence.

+ Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

+ The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

In [38]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [39]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [40]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


### Sorting a 2-D Array
- If you use the sort() method on a 2-D array, both arrays will be sorted:

In [41]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### NumPy Array Shape
+ The shape of an array is the number of elements in each dimension.
+ NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements.

**Print the shape of a 1-D array:**

In [112]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.shape)

(4,)


**Print the shape of a 2-D array:**

In [114]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


### NumPy Array Reshaping
+ Reshaping means changing the shape of an array.

+ The shape of an array is the number of elements in each dimension.

+ By reshaping we can add or remove dimensions or change number of elements in each dimension.

**Reshape From 1-D to 2-D**

In [115]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(4, 3)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Reshape From 1-D to 3-D**

In [116]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(2, 3, 2)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Flattening the arrays
+ Flattening array means converting a multidimensional array into a 1D array.

+ We can use `reshape(-1)` to do this.

In [118]:
# converting from 2-d to 1-d

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

newarr = arr.reshape(-1)

print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### NumPy Joining Array
+ Joining means putting contents of two or more arrays in a single array.

+ In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

+ We pass a sequence of arrays that we want to join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [119]:
# Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [120]:
# Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions
+ Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

+ We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

+ We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0.

In [121]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Stacking Along Rows
+ NumPy provides a helper function: `hstack()` to stack along rows.

In [122]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns
+ NumPy provides a helper function: `vstack()`  to stack along columns.

In [123]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth)
+ NumPy provides a helper function: `dstack()` to stack along height, which is the same as depth.

In [124]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### NumPy Searching Arrays
+ You can search an array for a certain value, and return the indexes that get a match.

+ To search an array, use the `where()` method.

In [125]:
# Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [126]:
# Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


### NumPy Filter Array
+ Getting some elements out of an existing array and creating a new array out of them is called filtering.

In [127]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)